### ISSUE TITLE
Split the library in two files .h and .cpp

### ISSUE THREAD

**Issue by maxbec** [sirleech/Webduino#58]
Hey sirleech,

for me i was not able to implement your library in my own library to use it there, until i found this post on the arduino forum: http://forum.arduino.cc/index.php?topic=120624.msg1006859#msg1006859

After i splitted your one .h file in an implementation and a header file everything compiled very well.
It would be no big deal to split the file and it would be really helpful if you could do so.

Kind Regards,
Max

**Comment by unwiredben** [comment]
When I originally wrote the library, I did it entirely as a header because it made it possible for a user to override options through #defines before they include the .h.

The code already supports this without needing to be split.  Just have

```
#define WEBDUINO_NO_IMPLEMENTATION
```

in all of the files that include this other than the first.  This will preprocess out all of the implementation code.

**Comment by unwiredben** [comment]
I don't understand your question.  All the the P() strings used by the
library are only defined in the implementation part of the header.  You
need one of your sources to not have the WEBDUINO_NO_IMPLEMENTATION
#define, without that you'd also not have the code implementation of the
library.
